import 'package:isar/isar.dart';

// Schema file generated by isar_generator — run separately:
//   dart pub global activate isar_generator
//   dart run build_runner build --delete-conflicting-outputs
// ignore: uri_has_not_been_generated
part 'cached_game.g.dart';

/// Cached game record for offline browsing of the user's collection.
/// TTL: 24 hours (see IsarService / CollectionRepository).
@collection
class CachedGame {
  Id id = Isar.autoIncrement;

  @Index(unique: true)
  late String serverId;

  late String name;
  String? imageUrl;
  String? thumbnailUrl;
  int? minPlayers;
  int? maxPlayers;
  int? minPlayTimeMinutes;
  int? maxPlayTimeMinutes;
  double? averageRating;
  int? bggId;
  late DateTime cachedAt;
}
