import 'package:isar/isar.dart';
import 'package:meeple_hearth/core/utils/app_logger.dart';
import 'package:path_provider/path_provider.dart';

// Collection imports — re-enable once isar_generator has been run:
//   dart pub global activate isar_generator
//   dart run build_runner build --delete-conflicting-outputs
// import 'package:meeple_hearth/core/storage/collections/cached_feed_item.dart';
// import 'package:meeple_hearth/core/storage/collections/cached_game.dart';
// import 'package:meeple_hearth/core/storage/collections/cached_notification.dart';
// import 'package:meeple_hearth/core/storage/collections/cached_user_game.dart';

/// Singleton managing the Isar local database instance.
///
/// Call [initialize] in `main()` before the app runs.
/// Access the database via [isar] after initialization.
///
/// **Schema generation:** Isar collection classes require code generation.
/// Run the following to generate schema files:
/// ```sh
/// dart pub global activate isar_generator 3.1.0+1
/// dart run build_runner build --delete-conflicting-outputs
/// ```
final class IsarService {
  IsarService._();

  static final IsarService instance = IsarService._();

  Isar? _isar;

  Isar get isar {
    assert(
      _isar != null,
      'IsarService has not been initialised. '
      'Call IsarService.instance.initialize() before use.',
    );
    return _isar!;
  }

  bool get isInitialized => _isar != null;

  Future<void> initialize() async {
    if (_isar != null) return;
    try {
      final dir = await getApplicationDocumentsDirectory();
      // Schema constants (CachedGameSchema etc.) are generated by isar_generator.
      // Run: dart pub global activate isar_generator
      //      dart run build_runner build --delete-conflicting-outputs
      // Then replace the empty list below with the generated schema constants.
      // ignore: prefer_const_literals_to_create_immutables
      _isar = await Isar.open(
        // ignore: inference_failure_on_collection_literal
        [],
        directory: dir.path,
        name: 'meeple_hearth_cache',
      );
      AppLogger.info('Isar database opened at ${dir.path}');
    } catch (e, st) {
      AppLogger.error('Failed to open Isar database', error: e, stackTrace: st);
      rethrow;
    }
  }

  Future<void> close() async {
    await _isar?.close();
    _isar = null;
  }

  /// Clears all cached data (e.g. on logout).
  Future<void> clearAll() async {
    if (_isar == null) return;
    await _isar!.writeTxn(() async {
      await _isar!.clear();
    });
  }
}
